-- CreateTable
CREATE TABLE `testex3` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `id_cliente` INTEGER NOT NULL,
    `config` VARCHAR(100) NOT NULL,
    `parametro` VARCHAR(256) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cliente_config_v2` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `id_cliente` INTEGER NOT NULL,
    `config` VARCHAR(100) NOT NULL,
    `parametro` VARCHAR(256) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `teste` (
    `idteste` INTEGER NOT NULL,

    PRIMARY KEY (`idteste`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `veiculos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `dataCadastro` DATETIME(0) NOT NULL,
    `dataAtualizacao` DATETIME(0) NOT NULL,
    `id_cliente_proprietario` INTEGER NULL DEFAULT 0,
    `id_cliente` INTEGER NOT NULL,
    `id_grupo` INTEGER NOT NULL,
    `id_grupo_sub` INTEGER NULL DEFAULT 0,
    `id_loja` INTEGER NULL,
    `grupo_gestao` VARCHAR(20) NULL,
    `placa` VARCHAR(7) NOT NULL,
    `placaMercosul` VARCHAR(7) NULL,
    `comPlacaMercosul` INTEGER NULL DEFAULT 0,
    `renavam` VARCHAR(11) NOT NULL,
    `marcaModelo` VARCHAR(50) NOT NULL DEFAULT '',
    `codigoMarca` INTEGER NOT NULL DEFAULT 0,
    `especie` VARCHAR(20) NOT NULL DEFAULT '',
    `tipo` VARCHAR(20) NOT NULL DEFAULT '',
    `ano_fabricacao` INTEGER NOT NULL DEFAULT 0,
    `ano_modelo` INTEGER NOT NULL DEFAULT 0,
    `chassi` VARCHAR(30) NOT NULL DEFAULT '',
    `cor` VARCHAR(15) NOT NULL DEFAULT '',
    `combustivel` VARCHAR(15) NOT NULL DEFAULT '',
    `potencia` VARCHAR(15) NOT NULL DEFAULT '',
    `municipio_veic` VARCHAR(50) NOT NULL DEFAULT '',
    `uf_veic` VARCHAR(2) NOT NULL DEFAULT '',
    `municipio_contrato` VARCHAR(50) NULL,
    `uf_contrato` VARCHAR(2) NULL,
    `sitVeiculo` VARCHAR(100) NOT NULL DEFAULT '',
    `nome_proprietario` VARCHAR(200) NULL,
    `cnpj_proprietario` VARCHAR(45) NULL,
    `cnpj` VARCHAR(25) NULL,
    `centro_custo` VARCHAR(20) NULL DEFAULT '',
    `status_localiza` VARCHAR(3) NULL,
    `ride_sharing` INTEGER NULL DEFAULT 0,
    `id_tipo_cobranca` INTEGER NULL DEFAULT 0,
    `dataVenda` DATE NULL,
    `status` INTEGER NOT NULL,
    `historico` TEXT NULL,
    `condutor_data_inicio` DATETIME(0) NULL,
    `condutor_nome` VARCHAR(254) NULL,
    `condutor_email` VARCHAR(254) NULL,
    `multasParcelamentoValor` DECIMAL(10, 2) NULL,
    `multasParcelamentoQtde` INTEGER NULL,
    `multasObrigatoriasValor` DECIMAL(10, 2) NULL,
    `multasObrigatoriasQtde` INTEGER NULL,
    `multasDefesaObrigatoriasValor` DECIMAL(10, 2) NULL,
    `multasDefesaObrigatoriasQtde` INTEGER NULL,
    `multasDefesaNObrigatoriasValor` DECIMAL(10, 2) NULL,
    `multasDefesaNObrigatoriasQtde` INTEGER NULL,
    `multasImpostasNaoVencidasValor` DECIMAL(10, 2) NULL,
    `multasImpostasNaoVencidasQtde` INTEGER NULL,
    `autoProcessoNotificacaoValor` DECIMAL(10, 2) NULL,
    `autoProcessoNotificacaoQtde` INTEGER NULL,
    `autoNotificadoValor` DECIMAL(10, 2) NULL,
    `autoNotificadoQtde` INTEGER NULL,
    `autoProcDefesaValor` DECIMAL(10, 2) NULL,
    `autoProcDefesaQtde` INTEGER NULL,
    `debIpvaAno1` INTEGER NULL,
    `debIpvaValor1` DECIMAL(10, 2) NULL,
    `debIpvaAno2` INTEGER NULL,
    `debIpvaValor2` DECIMAL(10, 2) NULL,
    `debIpvaAno3` INTEGER NULL,
    `debIpvaValor3` DECIMAL(10, 2) NULL,
    `debIpvaAno4` INTEGER NULL,
    `debIpvaValor4` DECIMAL(10, 2) NULL,
    `debIpvaAno5` INTEGER NULL,
    `debIpvaValor5` DECIMAL(10, 2) NULL,
    `debLicencAno` INTEGER NULL,
    `debLicencValor` DECIMAL(8, 2) NULL,
    `debLicencAnteriores` DECIMAL(8, 2) NULL,
    `debSeguroAno` INTEGER NULL,
    `debSeguroValor` DECIMAL(8, 2) NULL,
    `debSeguroAnteriores` DECIMAL(8, 2) NULL,
    `dataHoraUltimaConsulta` DATETIME(0) NULL,
    `dataHoraUltimaConsultaDerSp` DATETIME(0) NULL,
    `flagEntrouRestricao` INTEGER NULL DEFAULT 0,
    `flagSaiuRestricao` INTEGER NULL DEFAULT 0,
    `ipva_pago` VARCHAR(50) NULL,
    `seguro_pago` VARCHAR(50) NULL,
    `seguro_anterior_pago` VARCHAR(50) NULL,
    `taxa_licenciamento_paga` VARCHAR(120) NULL,
    `data_licenciamento` DATE NULL,
    `situacao_licenciamento` VARCHAR(150) NULL,
    `situacao_orgao` TEXT NULL,
    `erro_consulta_orgao` VARCHAR(120) NULL,
    `relatorio` INTEGER NOT NULL DEFAULT 0,
    `dataCompra` DATE NULL,
    `notaFiscal` VARCHAR(100) NULL,

    UNIQUE INDEX `placa_UNIQUE`(`placa`),
    INDEX `chassi`(`chassi`),
    INDEX `dataAtualizacao`(`dataAtualizacao`),
    INDEX `id_cliente`(`id_cliente`),
    INDEX `id_grupo`(`id_grupo`),
    INDEX `idx_veiculos_relatorio`(`relatorio`),
    INDEX `placa`(`placa`),
    INDEX `placaMercosul`(`placaMercosul`),
    INDEX `renavam`(`renavam`),
    INDEX `status`(`status`),
    INDEX `status_localiza`(`status_localiza`),
    PRIMARY KEY (`id`, `relatorio`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
